### ISSUE TITLE
Using with flextile patch

### ISSUE THREAD

**Issue by RaZ0rr-Two** [mihirlad55/dwm-anybar#10]
Flextile patch removes the following from dwm.c file. So, I am not able to apply any-bar patch to it. Is it possible to integrate them? Otherwise, as a workaround I can use deck layout patch.

```
-struct Monitor {
-	char ltsymbol[16];
-	float mfact;
-	int nmaster;
-	int num;
-	int by;               /* bar geometry */
-	int mx, my, mw, mh;   /* screen size */
-	int wx, wy, ww, wh;   /* window area  */
-	unsigned int seltags;
-	unsigned int sellt;
-	unsigned int tagset[2];
-	int showbar;
-	int topbar;
-	Client *clients;
-	Client *sel;
-	Client *stack;
-	Monitor *next;
-	Window barwin;
-	const Layout *lt[2];
-};
```

**Comment by RaZ0rr-Two** [comment]
Issue fixed. The corresponding functions are found in the `flextile.h` file added by [flextile patch](https://dwm.suckless.org/patches/flextile/). I think it only works if you patch flextile first and then add dwm-anybar patch. The other way around most probably won't work unless you manually patch everything carefully.

**Comment by mihirlad55** [comment]
Unfortunately, one of the limitations of dwm's patching system is that patching sometimes works best with particular patches before others. Thanks for verifying that it is possible to have both patches applied.
