### ISSUE TITLE
Emphasize that the bar script must be a forking kind

### ISSUE THREAD

**Issue by Ingvix** [mihirlad55/dwm-anybar#11]
I was wondering for bit what was the problem with my dwm freezing as launch until I realized my non-forking lemonbar script blocked the dwm from proceeding. Though it's mentioned that it's supposed to be a launching script, it still leaves it a bit vague. It wouldn't hurt to emphasize it, especially for the non-native english speakers.

**Comment by mihirlad55** [comment]
That's a good idea, I added it to the README. See commit 2c5b856.
