### ISSUE TITLE
Unmaintained Repository [DO NOT USE]

### ISSUE THREAD

**Issue by VeteranSquared** [mihirlad55/dwm-anybar#16]
There hasn't been a commit to "anybar" since the 7th of November, 2021, and so it is not compatible with the newer versions of Dwm. This complaint has already been raised by another person here, and the owner hasn't responded. Because of this, I will be messaging suckless to pull your unmaintained patch from their website.

**Comment by natehalsey** [comment]
Hi @VeteranSquared I've forked this repo and updated DWM to "maintain" this patch. Feel free to download the patch diff here: https://github.com/natehalsey/dwm-anybar/releases/download/v1.1.3/dwm-anybar-20240310-2c5b856.diff

Hopefully this helps!
