### ISSUE TITLE
Multiple bars

### ISSUE THREAD

**Issue by lockie** [mihirlad55/dwm-anybar#5]
Hello.
Suppose I have the polybar on top _and_ on bottom, with two different configs and different polybar processes. Would this patch work for that case?

**Comment by mihirlad55** [comment]
Hello,
The patch simply substitutes dwm's status bar for an external bar, and as such only supports any status bar management that dwm does with its own bar. dwm does not natively support two bars on the same monitor, so this patch does not either.

**Comment by lockie** [comment]
I see, thanks!
